---
format_version: 3
pipelines:
  "gocd-cli":
    group: gocd
    label_template: "${git[:8]}"
    locking: off
    materials:
      git:
        git: git@github.com:gocd-contrib/gocd-cli.git
    stages:
      - build:
          clean_workspace: true
          resources:
            - docker
          artifacts:
           - build:
               source: gocd
               destination:
          tasks:
           - exec:
               command: dojo
               arguments:
                - ./build.sh
